name: Build APK
on:
  workflow_dispatch
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: android-actions/setup-android@v3
      - name: Install SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Prepare Gradle wrapper (first run only)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.7"
      - name: Generate wrapper
        run: gradle wrapper --gradle-version 8.7
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
